"""Test questions for evaluating the RAG system."""

test_questions = [
    # Weather & Environment (get_weather, get_forecast, check_air_quality)
    ("What's the weather in Paris?", "get_weather"),
    ("Is it going to rain today?", "get_weather"),
    ("Should I bring an umbrella?", "get_weather"),
    ("What's it like outside?", "get_weather"),
    ("Next week's weather forecast", "get_forecast"),
    ("Will it be sunny this weekend?", "get_forecast"),
    ("How's the air quality today?", "check_air_quality"),
    ("Is it safe to go outside with pollution?", "check_air_quality"),
    # News & Information (get_news, search_wiki, get_trending, search_articles)
    ("Show me the latest tech news", "get_news"),
    ("What's happening in the world?", "get_news"),
    ("Any updates today?", "get_news"),
    ("Who was Albert Einstein?", "search_wiki"),
    ("Tell me about the Roman Empire", "search_wiki"),
    ("Look up quantum physics", "search_wiki"),
    ("I need info on climate change", "search_wiki"),
    ("What's trending on Twitter?", "get_trending"),
    ("Show me viral topics", "get_trending"),
    ("Find articles about AI", "search_articles"),
    ("Search news about elections", "search_articles"),
    # Health & Fitness (calc_bmi, track_calories, log_workout, get_health_tips)
    ("Calculate my BMI, I weigh 70kg and I'm 1.75m tall", "calc_bmi"),
    ("Am I overweight? 80kg, 1.8m", "calc_bmi"),
    ("How many calories in this burger?", "track_calories"),
    ("Log my food intake", "track_calories"),
    ("I ran 5km today", "log_workout"),
    ("Track my exercise", "log_workout"),
    ("Give me health advice", "get_health_tips"),
    ("How can I sleep better?", "get_health_tips"),
    # Language & Communication (translate, send_email, send_sms, grammar_check)
    ("Translate 'Hello world' to Spanish", "translate"),
    ("How do you say 'thank you' in French?", "translate"),
    ("I need translation help", "translate"),
    ("Send an email to john@example.com about the meeting", "send_email"),
    ("Contact my colleague", "send_email"),
    ("Write to the team", "send_email"),
    ("Text my friend", "send_sms"),
    ("Send a message to mom", "send_sms"),
    ("Check my writing for errors", "grammar_check"),
    ("Fix this sentence", "grammar_check"),
    # Data & Visualization (plot_chart, create_bar_chart, generate_report, export_csv)
    ("Create a line chart from sales_data.csv", "plot_chart"),
    ("Make a graph of this data", "plot_chart"),
    ("Visualize my numbers", "plot_chart"),
    ("Show me a bar graph", "create_bar_chart"),
    ("Create bars for comparison", "create_bar_chart"),
    ("Generate monthly report", "generate_report"),
    ("Make a PDF summary", "generate_report"),
    ("Export to spreadsheet", "export_csv"),
    ("Download as CSV", "export_csv"),
    # Travel & Transportation (search_flights, book_hotel, get_directions, check_traffic, find_parking)
    ("Find flights from New York to London on December 15th", "search_flights"),
    ("I need to fly to Tokyo", "search_flights"),
    ("Book me a plane ticket", "search_flights"),
    ("Find me a hotel in Miami", "book_hotel"),
    ("Where can I stay in Paris?", "book_hotel"),
    ("I need accommodation", "book_hotel"),
    ("How do I get from San Francisco to Palo Alto?", "get_directions"),
    ("Navigate me somewhere", "get_directions"),
    ("Show me the route", "get_directions"),
    ("Is there traffic on I-95?", "check_traffic"),
    ("How's the road?", "check_traffic"),
    ("Where can I park downtown?", "find_parking"),
    ("Find parking nearby", "find_parking"),
    # Finance & Money (get_stock_price, convert_currency, track_expenses, get_crypto_price, calculate_tax)
    ("What's the current price of Apple stock?", "get_stock_price"),
    ("How's Tesla doing?", "get_stock_price"),
    ("Check the market for me", "get_stock_price"),
    ("Convert 100 USD to Euros", "convert_currency"),
    ("Exchange rate calculator", "convert_currency"),
    ("What's the value in yen?", "convert_currency"),
    ("Log this purchase", "track_expenses"),
    ("Track my spending", "track_expenses"),
    ("How much is Bitcoin worth?", "get_crypto_price"),
    ("Check Ethereum price", "get_crypto_price"),
    ("Calculate tax on $50,000", "calculate_tax"),
    ("What's my tax liability?", "calculate_tax"),
    # Time & Productivity (get_time, set_reminder, create_calendar_event, set_timer, get_calendar)
    ("What time is it in Tokyo right now?", "get_time"),
    ("Current time in London?", "get_time"),
    ("Remind me to call mom tomorrow at 3pm", "set_reminder"),
    ("Don't let me forget this", "set_reminder"),
    ("I need to remember something", "set_reminder"),
    ("Schedule a meeting", "create_calendar_event"),
    ("Add to my calendar", "create_calendar_event"),
    ("Set timer for 10 minutes", "set_timer"),
    ("Start countdown", "set_timer"),
    ("What's on my schedule?", "get_calendar"),
    ("Show my agenda", "get_calendar"),
    ("View my calendar", "get_calendar"),
    ("What are my appointments?", "get_calendar"),
    ("Show me my upcoming events", "get_calendar"),
    # Math & Calculations (calculate, solve_equation, convert_units)
    ("What is 15% of 250?", "calculate"),
    ("Do some math for me", "calculate"),
    ("Compute 45 times 12", "calculate"),
    ("Solve x + 5 = 10", "solve_equation"),
    ("What's the solution?", "solve_equation"),
    ("Convert 5 miles to kilometers", "convert_units"),
    ("How many feet in 10 meters?", "convert_units"),
    # Food & Dining (book_restaurant, search_recipes, order_food, find_restaurants)
    ("Book a table for 4 at Italian restaurant tonight at 7pm", "book_restaurant"),
    ("I'm planning dinner", "book_restaurant"),
    ("Reserve a spot for tonight", "book_restaurant"),
    ("Find me a recipe for chicken curry", "search_recipes"),
    ("What can I cook tonight?", "search_recipes"),
    ("I need cooking ideas", "search_recipes"),
    ("Order pizza delivery", "order_food"),
    ("Get me food from that Thai place", "order_food"),
    ("Find Chinese restaurants nearby", "find_restaurants"),
    ("Where can I eat sushi?", "find_restaurants"),
    # Entertainment & Media (search_movies, get_book_info, search_music)
    ("What movies are playing tonight?", "search_movies"),
    ("Find showtimes for Avatar", "search_movies"),
    ("Tell me about '1984' book", "get_book_info"),
    ("Who wrote this novel?", "get_book_info"),
    ("Find songs by Taylor Swift", "search_music"),
    ("Play my favorite music", "search_music"),
    # Smart Home (control_lights, set_thermostat)
    ("Turn on the lights", "control_lights"),
    ("Dim the bedroom lights", "control_lights"),
    ("Set temperature to 72 degrees", "set_thermostat"),
    ("Make it warmer", "set_thermostat"),
    # Shopping (search_products, track_package, compare_prices)
    ("Find me a new laptop", "search_products"),
    ("Search for running shoes", "search_products"),
    ("Where's my package?", "track_package"),
    ("Track my delivery", "track_package"),
    ("Compare prices for iPhone", "compare_prices"),
    ("Find the best deal", "compare_prices"),
    # Negative test cases - NO correct tool exists
    ("What is the meaning of life?", None),
    ("Tell me a joke", None),
    ("How do I fix my broken laptop?", None),
    ("What's the capital of France?", None),
    ("Play some music", None),
]
